### PR TITLE
Using cookiecutter, the usual boilerplate was added to the module.

### LINKED ISSUE #3: Add Python packaging metadata
The usual python packaging metadata should be added to SwiftBulkUploaded, so that the module could be added to pypi.

### PR DESCRIPTION
**Pull request by cudevmaxwell**
This fixes #3.

### CODE REVIEW

**Comment by cudevmaxwell** [comment]
So, this PR adds quite a lot of files, but it doesn't change the core application code very much. The only change there was adding a main() function to the two python scripts that are run as command line applications. That was done so that, when using virtualenv+pip, bulkupload and prepareupload are added to the PATH as executables. 

With this change (and by removing the mysql requirement), the instructions to use the tool will be much simpler: 

0) Install virtualenv (to isolate the application and it's requirements, a recommended but not required step).
1) `pip install swiftbulkuploader`
2) `prepareupload ...` and `bulkupload ...`

**Comment by cudevmaxwell** [comment]
If anyone with more python packaging experience sees anything I'm missing or did wrong, please let us know!

**Comment by cudevmaxwell** [comment]
Also, this exposes the email alias we've been using as the contact email for the package. I don't know if  we want to do that.

**Comment by cudevmaxwell** [comment]
@ruebot, I think that's the best bet.

**Comment by Petahhh** [comment]
Thank you @cudevmaxwell @ruebot! So far these look amazing. Will be merging them shortly after some testing.

Thanks again!

**Pull request merged**
